version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.16.5"
      ONLINE_MODE: 0 
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
